#!/usr/bin/env bash

# solution to Webstack Debugging #1 challenge
# Approach: Eliminates faulty symlinks to Nginx server block config file
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start

